routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/profiles', 'ProfileController@index')->name('profiles.index');
Route::get('/profiles/create', 'ProfileController@create')->name('profiles.create');
Route::post('/profiles', 'ProfileController@store')->name('profiles.store');
Route::get('/profiles/{id}', 'ProfileController@show')->name('profiles.show');
Route::post('/profiles/{id}', 'ProfileController@update')->name('profiles.update');
Route::get('/profiles/{id}/delete', 'ProfileController@destroy')->name('profiles.destroy');

Route::get('/admin/login', 'Admin\LoginAdminController@showLoginForm')->name('admin.showLoginForm');
Route::post('/admin/processlogin', 'Admin\LoginAdminController@login')->name('admin.login');

Route::group(['middleware' => ['auth','admin']], function() {
  Route::prefix('admin')->group(function () {
    //

    	//Dashboard
  		Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard.index');

    	//SociaL Network
    	Route::resource('/socialnetworks', 'Admin\SocialNetworkController');

    	//Profile Company
    	Route::resource('/profilecompany', 'Admin\ProfileCompanyController');

    	//Ads Index
    	Route::resource('/adsindex', 'Admin\AdsIndexController');

		//Ads Category
		Route::resource('/adscategories', 'Admin\AdsCategoryController');

		//Ads Checkout
		Route::resource('/adscheckouts', 'Admin\AdsCheckoutController');
	
		//Offer Limit
		Route::resource('/offerlimits', 'Admin\OfferLimitController');

    	//Sliders
    	Route::resource('/sliders', 'Admin\SliderController');

  		//Order
    	Route::get('/orders', 'OrderController@index')->name('orders.index');
		Route::get('/orders/create', 'OrderController@create')->name('orders.create');
		Route::post('/orders', 'OrderController@store')->name('orders.store');
		Route::get('/orders/{id}', 'OrderController@show')->name('orders.show');
		Route::post('/orders/{id}', 'OrderController@update')->name('orders.update');
		Route::get('/orders/{id}/delete', 'OrderController@destroy')->name('orders.destroy');

		//Tax
		Route::resource('/tax', 'Admin\TaxController');

	  	//Status
	  	Route::resource('/status', 'Admin\StatuController');

		//Address
		Route::get('/addresses', 'AddressController@index')->name('address.index');
		Route::get('/addresses/create', 'AddressController@create')->name('address.create');
		Route::post('/addresses', 'AddressController@store')->name('address.store');
		Route::get('/addresses/{id}', 'AddressController@show')->name('address.show');
		Route::post('/addresses/{id}', 'AddressController@update')->name('address.update');
		Route::get('/addresses/{id}/delete', 'AddressController@destroy')->name('address.destroy');

		//Shipping_companies
		Route::resource('/shippingcompanies', 'Admin\ShippingCompanyController');
		
		//Credit_card
		Route::get('/creditcards', 'CreditCardController@index')->name('creditcards.index');
		Route::get('/creditcards/create', 'CreditCardController@create')->name('creditcards.create');
		Route::post('/creditcards', 'CreditCardController@store')->name('creditcards.store');
		Route::get('/creditcards/{id}', 'CreditCardController@show')->name('creditcards.show');
		Route::post('/creditcards/{id}', 'CreditCardController@update')->name('creditcards.update');
		Route::get('/creditcards/{id}/delete', 'CreditCardController@destroy')->name('creditcards.destroy');
		
		//Categories
		Route::resource('/categories', 'Admin\CategoryController');

		//Brands
		Route::resource('/brands', 'Admin\BrandController');

		//Products
		Route::resource('/products', 'Admin\ProductController');

		//Label
		Route::resource('/labels', 'Admin\LabelController');
		
		//Payment_methods
		Route::resource('/paymentmethods', 'Admin\PaymentMethodController');

		//Comments
		Route::get('/comments', 'CommentController@index')->name('comments.index');
		Route::get('/comments/create', 'CommentController@create')->name('comments.create');
		Route::post('/comments/create', 'CommentController@store')->name('comments.store');
		Route::get('/comments/{slug}', 'CommentController@show')->name('comments.show');
		Route::post('/comments/{slug}', 'CommentController@update')->name('comments.update');
		Route::get('/comments/{slug}/delete', 'CommentController@destroy')->name('comments.destroy');

		//Top Categories
		Route::resource('/settingtopcategories', 'Admin\SettingTopcategoryController');

		//Top Menus
		Route::resource('/settingtopmenus', 'Admin\SettingTopmenuController');
		
	//
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::post('/register', 'RegisterPublicController@register')->name('index.register');


Route::get('/', 'IndexController@index')->name('index.index');
//Route::get('/home', 'HomeController@index')->name('home');
Route::redirect('/home', '/');

//index Categories
Route::get('/categories', 'IndexController@allCategory')->name('index.allCategories');
Route::get('/categories/{slug}', 'IndexController@singleCategories')->name('index.singleCategories');

//index products
Route::get('/products', 'IndexController@allProducts')->name('index.allProducts');
Route::get('/products/{slug}', 'IndexController@singleProduct')->name('index.singleProduct');

//cart shop
Route::get('/cart', 'CartController@cart')->name('cart.index');
Route::get('/cart/{id}/add', 'CartController@addCart')->name('cart.addCart');
Route::get('/cart/{id}/delete', 'CartController@destroyCart')->name('cart.destroyCart');
Route::get('/cart/empty', 'CartController@emptyCart')->name('cart.emptyCart');

//checkout
Route::get('/checkout/step_1', 'CheckOutController@checkoutStep_1')->name('checkout.checkoutStep_1');
Route::post('/checkout/step_2', 'CheckOutController@checkoutStep_2')->name('checkout.checkoutStep_2');
Route::post('/checkout/step_3', 'CheckOutController@checkoutStep_3')->name('checkout.checkoutStep_3');
Route::post('/checkout/step_4', 'CheckOutController@checkoutStep_4')->name('checkout.checkoutStep_4');
Route::post('/checkout/step_login', 'CheckOutController@checkoutStep_login')->name('checkout.checkoutStep_login');
Route::post('/checkout/step_processlogin', 'LoginCheckoutController@login')->name('checkout.checkoutStep_processlogin');

Route::post('/checkout/step_register', 'CheckOutController@checkoutStep_register')->name('checkout.checkoutStep_register');
Route::post('/checkout/step_processregister', 'RegisterCheckoutController@register')->name('checkout.register');

Route::post('/checkout/step_order', 'CheckOutController@checkoutStep_order')->name('checkout.checkoutStep_order');

//Abouts
Route::get('/abouts', 'IndexController@about')->name('abouts.about');

//Contact us
Route::get('/contacts', 'IndexController@contact')->name('abouts.contact');


Route::group(['middleware' => ['auth']], function() {	
	Route::get('/checkout/step_5', 'CheckOutController@checkoutStep_5')->name('checkout.checkoutStep_5');

	//Users Public
	Route::redirect('/users', '/users/profile');
	Route::get('/users/profile', 'UserPublicController@profile')->name('users.profile');
	Route::post('/users/profile', 'UserPublicController@profileStore')->name('users.profileStore');
	Route::get('/users/address', 'UserPublicController@address')->name('users.address');
	Route::post('/users/address', 'UserPublicController@addressStore')->name('users.addressStore');
	Route::get('/users/orders', 'UserPublicController@order')->name('users.order');
	Route::get('/users/orders/{id}/invoice', 'UserPublicController@download')->name('users.download');

});

resources/views/admin/tables/adsCategoryTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Ads-Category
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Ads Category <a href="{{route('adscategories.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Url</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($adsCategories as $adsCategory)
                    <tr>
                      <td>{{ $adsCategory->title }}</td>
                      <td>{{ $adsCategory->url }}</td>
                      <td>
                        <a href="{{route('adscategories.show', $adsCategory->id)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$adsCategory->id}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('adscategories.destroy', $adsCategory->id) }}" id="delete-{{$adsCategory->id}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/adsCheckoutTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Ads-Checkout
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Ads Checkout <a href="{{route('adscheckouts.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Url</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($adsCheckouts as $adsCheckout)
                    <tr>
                      <td>{{ $adsCheckout->title }}</td>
                      <td>{{ $adsCheckout->url }}</td>
                      <td>
                        <a href="{{route('adscheckouts.show', $adsCheckout->id)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$adsCheckout->id}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('adscheckouts.destroy', $adsCheckout->id) }}" id="delete-{{$adsCheckout->id}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/adsIndexTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Ads-Index
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Ads Index <a href="{{route('adsindex.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Url</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($adsIndexs as $adsIndex)
                    <tr>
                      <td>{{ $adsIndex->title }}</td>
                      <td>{{ $adsIndex->url }}</td>
                      <td>
                        <a href="{{route('adsindex.show', $adsIndex->id)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$adsIndex->id}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('adsindex.destroy', $adsIndex->id) }}" id="delete-{{$adsIndex->id}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/brandTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Brands
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Brands <a href="{{route('brands.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>SEO Url</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($brands as $brand)
                    <tr>
                      <td>{{ $brand->name }}</td>
                      <td>{{ $brand->slug }}</td>
                      <td>
                        <a href="{{route('brands.show', $brand->slug)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$brand->slug}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('brands.destroy', $brand->slug) }}" id="delete-{{$brand->slug}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/categoryTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Categories
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Categories <a href="{{route('categories.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>SEO Url</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($categories as $category)
                    <tr>
                      <td>{{ $category->title }}</td>
                      <td>{{ $category->description }}</td>
                      <td>{{ $category->slug }}</td>
                      <td>
                        <a href="{{route('categories.show', $category->slug)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$category->slug}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('categories.destroy', $category->slug) }}" id="delete-{{$category->slug}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/labelTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Labels
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Labels <a href="{{route('labels.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>SEO Url</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($labels as $label)
                    <tr>
                      <td>{{ $label->name }}</td>
                      <td>{{ $label->slug }}</td>
                      <td>
                        <a href="{{route('labels.show', $label->slug)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$label->slug}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('labels.destroy', $label->slug) }}" id="delete-{{$label->slug}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/offerLimitTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Offer-Limits
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Offer Limits <a href="{{route('offerlimits.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Title </th>
                    <th>Subtitle </th>
                    <th>Description </th>
                    <th>Url </th>
                    <th>Date End </th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($offerLimits as $offerLimit)
                    <tr>
                      <td>{{ $offerLimit->title }}</td>
                      <td>{{ $offerLimit->subtitle }}</td>
                      <td>{{ $offerLimit->description }}</td>
                      <td>{{ $offerLimit->url }}</td>
                      <td>{{ $offerLimit->date_end }}</td>
                      <td>
                        <a href="{{route('offerlimits.show', $offerLimit->id)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$offerLimit->id}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('offerlimits.destroy', $offerLimit->id) }}" id="delete-{{$offerLimit->id}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/productTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Products
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Products <a href="{{route('products.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Title </th>
                    <th>Short-Description </th>
                    <th>Large-Description </th>
                    <th>Amount </th>
                    <th>Unit </th>
                    <th>SEO Url </th>
                    <th>Category </th>
                    <th>Brand </th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($products as $product)
                    <tr>
                      <td>{{ $product->title }}</td>
                      <td>{{ $product->short_description }}</td>
                      <td>{{ $product->large_description }}</td>
                      <td>${{formatMoney($product->amount)}}</td>
                      <td>{{ $product->unit }}</td>
                      <td>{{ $product->slug }}</td>
                      <td>{{ $product->category->title }}</td>
                      <td>{{ $product->brand->name }}</td>
                      <td>
                        <a href="{{route('products.show', $product->slug)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$product->slug}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('products.destroy', $product->slug) }}" id="delete-{{$product->slug}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/profileCompanyTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Profile Companies
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Profile Companies <a href="{{route('profilecompany.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Name Trade </th>
                    <th>Name Legal </th>
                    <th>Email </th>
                    <th>Phone Local </th>
                    <th>Address 1 </th>
                    <th>City </th>
                    <th>Country </th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($profileCompanies as $profileCompany)
                    <tr>
                      <td>{{ $profileCompany->name_trade }}</td>
                      <td>{{ $profileCompany->name_legal }}</td>
                      <td>{{ $profileCompany->email }}</td>
                      <td>{{ $profileCompany->phone_local }}</td>
                      <td>{{ $profileCompany->address_1 }}</td>
                      <td>{{ $profileCompany->city }}</td>
                      <td>{{ $profileCompany->country }}</td>
                      <td>
                        <a href="{{route('profilecompany.show', $profileCompany->id)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$profileCompany->id}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('profilecompany.destroy', $profileCompany->id) }}" id="delete-{{$profileCompany->id}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection

resources/views/admin/tables/settingTopcategoryTable.blade.php
@extends('admin.layouts.adminLayout')

@section('title')
  Setting-Top-Categories
@endsection

@section('contentAdmin')
  <main class="content">
    <div class="container-fluid p-0">

      <h1 class="h3 mb-3">Setting Top Categories <a href="{{route('settingtopcategories.create')}}">Crear</a></h1>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table id="datatables-basic" class="table table-striped" style="width:100%">
                <thead>
                  <tr>
                    <th>Category</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($settingTopcategories as $settingTopcategory)
                    <tr>
                      <td>{{ $settingTopcategory->category->title }}</td>
                      <td>
                        <a href="{{route('settingtopcategories.show', $settingTopcategory->id)}}"><i class="align-middle mr-2 far fa-fw fa-edit"></i></a>
                        <a href="" onclick="event.preventDefault(); deleteForm('delete-{{$settingTopcategory->id}}')"><i class="align-middle mr-2 fas fa-fw fa-trash-alt"></i></a>
                        <form style="display: none;" action="{{ route('settingtopcategories.destroy', $settingTopcategory->id) }}" id="delete-{{$settingTopcategory->id}}" method="POST">
                          @csrf
                          @method('DELETE')
                        </form>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </main>
@endsection

@section('js')
  <script>
    $(function() {
      // Datatables basic
      $("#datatables-basic").DataTable({
        responsive: true
      });
    });
  </script>
  <script>
    function deleteForm(name) {
      let form = document.getElementById(name);
      form.submit();
    }
  </script>
@endsection