routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/profiles', 'ProfileController@index')->name('profiles.index');
Route::get('/profiles/create', 'ProfileController@create')->name('profiles.create');
Route::post('/profiles', 'ProfileController@store')->name('profiles.store');
Route::get('/profiles/{id}', 'ProfileController@show')->name('profiles.show');
Route::post('/profiles/{id}', 'ProfileController@update')->name('profiles.update');
Route::get('/profiles/{id}/delete', 'ProfileController@destroy')->name('profiles.destroy');

Route::get('/admin/login', 'Admin\LoginAdminController@showLoginForm')->name('admin.showLoginForm');
Route::post('/admin/processlogin', 'Admin\LoginAdminController@login')->name('admin.login');

Route::group(['middleware' => ['auth','admin']], function() {
  Route::prefix('admin')->group(function () {
    //

    	//Dashboard
  		Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard.index');

    	//SociaL Network
    	Route::resource('/socialnetworks', 'Admin\SocialNetworkController');

    	//Profile Company
    	Route::resource('/profilecompany', 'Admin\ProfileCompanyController');

    	//Ads Index
    	Route::resource('/adsindex', 'Admin\AdsIndexController');

		//Ads Category
		Route::resource('/adscategories', 'Admin\AdsCategoryController');

		//Ads Checkout
		Route::resource('/adscheckouts', 'Admin\AdsCheckoutController');
	
		//Offer Limit
		Route::resource('/offerlimits', 'Admin\OfferLimitController');

    	//Sliders
    	Route::resource('/sliders', 'Admin\SliderController');

  		//Order
    	Route::get('/orders', 'OrderController@index')->name('orders.index');
		Route::get('/orders/create', 'OrderController@create')->name('orders.create');
		Route::post('/orders', 'OrderController@store')->name('orders.store');
		Route::get('/orders/{id}', 'OrderController@show')->name('orders.show');
		Route::post('/orders/{id}', 'OrderController@update')->name('orders.update');
		Route::get('/orders/{id}/delete', 'OrderController@destroy')->name('orders.destroy');

		//Tax
		Route::resource('/tax', 'Admin\TaxController');

	  	//Status
	  	Route::resource('/status', 'Admin\StatuController');

		//Address
		Route::get('/addresses', 'AddressController@index')->name('address.index');
		Route::get('/addresses/create', 'AddressController@create')->name('address.create');
		Route::post('/addresses', 'AddressController@store')->name('address.store');
		Route::get('/addresses/{id}', 'AddressController@show')->name('address.show');
		Route::post('/addresses/{id}', 'AddressController@update')->name('address.update');
		Route::get('/addresses/{id}/delete', 'AddressController@destroy')->name('address.destroy');

		//Shipping_companies
		Route::resource('/shippingcompanies', 'Admin\ShippingCompanyController');
		
		//Credit_card
		Route::get('/creditcards', 'CreditCardController@index')->name('creditcards.index');
		Route::get('/creditcards/create', 'CreditCardController@create')->name('creditcards.create');
		Route::post('/creditcards', 'CreditCardController@store')->name('creditcards.store');
		Route::get('/creditcards/{id}', 'CreditCardController@show')->name('creditcards.show');
		Route::post('/creditcards/{id}', 'CreditCardController@update')->name('creditcards.update');
		Route::get('/creditcards/{id}/delete', 'CreditCardController@destroy')->name('creditcards.destroy');
		
		//Categories
		Route::resource('/categories', 'Admin\CategoryController');

		//Brands
		Route::resource('/brands', 'Admin\BrandController');

		//Products
		Route::resource('/products', 'Admin\ProductController');

		//Label
		Route::resource('/labels', 'Admin\LabelController');
		
		//Payment_methods
		Route::resource('/paymentmethods', 'Admin\PaymentMethodController');

		//Comments
		Route::get('/comments', 'CommentController@index')->name('comments.index');
		Route::get('/comments/create', 'CommentController@create')->name('comments.create');
		Route::post('/comments/create', 'CommentController@store')->name('comments.store');
		Route::get('/comments/{slug}', 'CommentController@show')->name('comments.show');
		Route::post('/comments/{slug}', 'CommentController@update')->name('comments.update');
		Route::get('/comments/{slug}/delete', 'CommentController@destroy')->name('comments.destroy');

		//Top Categories
		Route::resource('/settingtopcategories', 'Admin\SettingTopcategoryController');

		//Top Menus
		Route::resource('/settingtopmenus', 'Admin\SettingTopmenuController');
		
	//
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::post('/register', 'RegisterPublicController@register')->name('index.register');


Route::get('/', 'IndexController@index')->name('index.index');
//Route::get('/home', 'HomeController@index')->name('home');
Route::redirect('/home', '/');

//index Categories
Route::get('/categories', 'IndexController@allCategory')->name('index.allCategories');
Route::get('/categories/{slug}', 'IndexController@singleCategories')->name('index.singleCategories');

//index products
Route::get('/products', 'IndexController@allProducts')->name('index.allProducts');
Route::get('/products/{slug}', 'IndexController@singleProduct')->name('index.singleProduct');

//cart shop
Route::get('/cart', 'CartController@cart')->name('cart.index');
Route::get('/cart/{id}/add', 'CartController@addCart')->name('cart.addCart');
Route::get('/cart/{id}/delete', 'CartController@destroyCart')->name('cart.destroyCart');
Route::get('/cart/empty', 'CartController@emptyCart')->name('cart.emptyCart');

//checkout
Route::get('/checkout/step_1', 'CheckOutController@checkoutStep_1')->name('checkout.checkoutStep_1');
Route::post('/checkout/step_2', 'CheckOutController@checkoutStep_2')->name('checkout.checkoutStep_2');
Route::post('/checkout/step_3', 'CheckOutController@checkoutStep_3')->name('checkout.checkoutStep_3');
Route::post('/checkout/step_4', 'CheckOutController@checkoutStep_4')->name('checkout.checkoutStep_4');
Route::post('/checkout/step_login', 'CheckOutController@checkoutStep_login')->name('checkout.checkoutStep_login');
Route::post('/checkout/step_processlogin', 'LoginCheckoutController@login')->name('checkout.checkoutStep_processlogin');

Route::post('/checkout/step_register', 'CheckOutController@checkoutStep_register')->name('checkout.checkoutStep_register');
Route::post('/checkout/step_processregister', 'RegisterCheckoutController@register')->name('checkout.register');

Route::post('/checkout/step_order', 'CheckOutController@checkoutStep_order')->name('checkout.checkoutStep_order');

//Abouts
Route::get('/abouts', 'IndexController@about')->name('abouts.about');

//Contact us
Route::get('/contacts', 'IndexController@contact')->name('abouts.contact');


Route::group(['middleware' => ['auth']], function() {	
	Route::get('/checkout/step_5', 'CheckOutController@checkoutStep_5')->name('checkout.checkoutStep_5');

	//Users Public
	Route::redirect('/users', '/users/profile');
	Route::get('/users/profile', 'UserPublicController@profile')->name('users.profile');
	Route::post('/users/profile', 'UserPublicController@profileStore')->name('users.profileStore');
	Route::get('/users/address', 'UserPublicController@address')->name('users.address');
	Route::post('/users/address', 'UserPublicController@addressStore')->name('users.addressStore');
	Route::get('/users/orders', 'UserPublicController@order')->name('users.order');
	Route::get('/users/orders/{id}/invoice', 'UserPublicController@download')->name('users.download');

});

resources/views/forms/addressCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Address</title>
</head>
<body>
<form  action="{{ route('address.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">


  <label for="fullname">User :</label>
  <select name="user_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($users as $user)
      <option value="{{ $user->id }}">{{ $user->name }}</option>
    @endforeach
  </select>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">First Name  :</label>
    <input type="text" name="first_name" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Last Name  :</label>
    <input type="text" name="last_name" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Emal  :</label>
    <input type="email" name="email" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Phone  :</label>
    <input type="text" name="phone" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Company  :</label>
    <input type="text" name="company" class="form-control" />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Country  :</label>
    <input type="text" name="country" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">City  :</label>
    <input type="text" name="city" class="form-control" />
  </div>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Code Postal  :</label>
    <input type="number" name="code_postal" class="form-control" required />
  </div>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Address 1  :</label>
    <input type="text" name="address_1" class="form-control" required />
  </div>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Address 2  :</label>
    <input type="text" name="address_2" class="form-control" />
  </div>

         
  <br>

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Crear</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/addressUpdateForm.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>Edit Product</title>
</head>
<body>
<form  action="/admin/addresses/{{$address->id}}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <label for="fullname">User :</label>
  <select name="user_id" class="form-control" required >
    @foreach($users as $user)
      <option value="{{ $user->id }}" 
        @if($user->id == $address->user_id)
          selected=""
        @endif
        >{{ $user->name }}</option>
    @endforeach
  </select>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">First Name  :</label>
    <input type="text" name="first_name" class="form-control" value="{{ $address->first_name }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Last Name  :</label>
    <input type="text" name="last_name" class="form-control" value="{{ $address->last_name }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Email  :</label>
    <input type="email" name="email" class="form-control" value="{{ $address->email }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Phone  :</label>
    <input type="text" name="phone" class="form-control" value="{{ $address->phone }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Company  :</label>
    <input type="text" name="company" class="form-control" value="{{ $address->company }}" />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Country  :</label>
    <input type="text" name="country" class="form-control" value="{{ $address->country }}" required />
  </div>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">City :</label>
    <input type="text" name="city" class="form-control" value="{{ $address->city }}" />
  </div>

   <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Code Postal :</label>
    <input type="number" name="code_postal" class="form-control" value="{{ $address->code_postal }}" required />
  </div>

  <br>
  
  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Address 1 :</label>
    <input type="text" name="address_1" class="form-control" value="{{ $address->address_1 }}" required />
  </div>

  <br>
  
  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Address 2 :</label>
    <input type="text" name="address_2" class="form-control" value="{{ $address->address_2 }}" />
  </div>
         
  <br>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Editar</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/commentCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Comment</title>
</head>
<body>
<form  action="{{ route('comments.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Content  :</label>
    <input type="text" name="content" class="form-control" required />
  </div>

  <br>

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Crear</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/commentUpdateForm.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Edit Comment</title>
</head>
<body>
<form  action="/admin/comments/{{ $comment->id }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Content  :</label>
    <input type="text" name="content" class="form-control" value="{{ $comment->content }}" required />
  </div>

  <br>

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Editar</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/creditCardCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Credit Card</title>
</head>
<body>
<form  action="{{ route('creditcards.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">


  <label for="fullname">User :</label>
  <select name="user_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($users as $user)
      <option value="{{ $user->id }}">{{ $user->name }}</option>
    @endforeach
  </select>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Card Number  :</label>
    <input type="number" name="card_number" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Name  :</label>
    <input type="text" name="name" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Expire  :</label>
    <input type="text" name="expire" class="form-control" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">CVC  :</label>
    <input type="number" name="cvc" class="form-control" required />
  </div>
         
  <br>

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Crear</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/creditCardUpdateForm.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>Edit Credit Card</title>
</head>
<body>
<form  action="/admin/creditcards/{{$creditcard->id}}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <label for="fullname">User :</label>
  <select name="user_id" class="form-control" required >
    @foreach($users as $user)
      <option value="{{ $user->id }}" 
        @if($user->id == $creditcard->user_id)
          selected=""
        @endif
        >{{ $user->name }}</option>
    @endforeach
  </select>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Card Number  :</label>
    <input type="number" name="card_number" class="form-control" value="{{ $creditcard->card_number }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Name  :</label>
    <input type="text" name="name" class="form-control" value="{{ $creditcard->name }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Expire  :</label>
    <input type="text" name="expire" class="form-control" value="{{ $creditcard->expire }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">CVC  :</label>
    <input type="number" name="cvc" class="form-control" value="{{ $creditcard->cvc }}" required />
  </div>
         
  <br>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Editar</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/orderCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Order</title>
</head>
<body>
<form  action="{{ route('orders.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">


  <label for="fullname">User :</label>
  <select name="user_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($users as $user)
      <option value="{{ $user->id }}">{{ $user->name }}</option>
    @endforeach
  </select>

  <br>

  <label for="fullname">Address :</label>
  <select name="address_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($addresses as $address)
      <option value="{{ $address->id }}">{{ $address->first_name }}</option>
    @endforeach
  </select>

   <br>

  <label for="fullname">Payment Method :</label>
  <select name="payment_method_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($paymentMethods as $paymentMethod)
      <option value="{{ $paymentMethod->id }}">{{ $paymentMethod->name }}</option>
    @endforeach
  </select>

  <br>

  <label for="fullname">Statu :</label>
  <select name="statu_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($status as $statu)
      <option value="{{ $statu->id }}">{{ $statu->name }}</option>
    @endforeach
  </select>

  <br>

  <label for="fullname">Shipping Company :</label>
  <select name="shipping_company_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($shippingCompanies as $shippingCompany)
      <option value="{{ $shippingCompany->id }}">{{ $shippingCompany->name }}</option>
    @endforeach
  </select>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Total  :</label>
    <input type="number" name="total" class="form-control" />
  </div>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Subtotal  :</label>
    <input type="number" name="subtotal" class="form-control" />
  </div>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Tax  :</label>
    <input type="number" name="tax" class="form-control" />
  </div>



    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Crear</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/profileCompanyCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Profile Company</title>
</head>
<body>
  <form  action="{{ route('profileCompany.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
      @csrf
    <div class="row">


      <div class="col-md-4 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Name Trade  :</label>
        <input type="text" name="name_trade" class="form-control" required />
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Name Legal  :</label>
        <input type="text" name="name_legal" class="form-control" required />
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Emal  :</label>
        <input type="email" name="email" class="form-control" required />
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Phone Local  :</label>
        <input type="text" name="phone_local" class="form-control" required />
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Phone Mobile  :</label>
        <input type="text" name="phone_mobile" class="form-control" />
      </div>

      <br>

      <div class="col-md-4 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Address 1  :</label>
        <input type="text" name="address_1" class="form-control" required />
      </div>

      <br>

      <div class="col-md-4 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Address 2  :</label>
        <input type="text" name="address_2" class="form-control" />
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">City  :</label>
        <input type="text" name="city" class="form-control" required/>
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Region  :</label>
        <input type="text" name="region" class="form-control" />
      </div>

      <br>

      <div class="col-md-8 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Country  :</label>
        <input type="text" name="country" class="form-control" required />
      </div>

      <br>

      <div class="col-md-4 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Logo  :</label>
        <input type="file" name="logo" class="form-control" required />
      </div>

      <br>

      <div class="col-md-4 col-sm-12 col-xs-12 form-group">
        <label for="fullname">Favicon  :</label>
        <input type="file" name="favicon" class="form-control" required />
      </div>

      <br>

      <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Crear</button>
      </div>

    </div>
  </form>

</body>
</html>

resources/views/forms/settingTopcategoryCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Product</title>
</head>
<body>
<form  action="{{ route('topcategories.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
  <div class="row">
  
  <label for="fullname">Category :</label>
  <select name="category_id" class="form-control" required >
    <option value="">Seleccione una opcion ...</option>
    @foreach($categories as $category)
      <option value="{{ $category->id }}">{{ $category->title }}</option>
    @endforeach
  </select>

  <br> 

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Crear</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/settingTopcategoryUpdateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Edit Setting Category</title>
</head>
<body>
<form  action="/admin/settingtopcategories/{{ $SettingTopcategory->id }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <label for="fullname">Categoria :</label>
  <select name="category_id" class="form-control" required >
    @foreach($categories as $category)
      <option value="{{ $category->id }}" 
        @if($category->id == $SettingTopcategory->category_id)
          selected=""
        @endif
        >{{ $category->title }}</option>
    @endforeach
  </select>

  <br>

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Editar</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/socialNetworkUpdateForm.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>Edit Social Network</title>
</head>
<body>
<form  action="/admin/socialnetworks/{{$socialNetwork->id}}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <label for="fullname">Profile Company :</label>
  <select name="profile_company_id" class="form-control" required >
    @foreach($profileCompanies as $profileCompany)
      <option value="{{ $profileCompany->id }}" 
        @if($profileCompany->id == $socialNetwork->user_id)
          selected=""
        @endif
        >{{ $profileCompany->name_trade }}</option>
    @endforeach
  </select>

  <br>

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Name  :</label>
    <input type="text" name="name" class="form-control" value="{{ $socialNetwork->name }}" required />
  </div>

  <br>

  <div class="col-md-8 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Url  :</label>
    <input type="text" name="url" class="form-control" value="{{ $socialNetwork->url }}" required />
  </div>

  <br>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Editar</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/taxCreateFrom.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Create Tax</title>
</head>
<body>
<form  action="{{ route('tax.store') }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
<div class="row">

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Amount  :</label>
    <input type="numeric" name="amount" class="form-control" required />
  </div>

  <br>

    <div class="modal-footer">
      	<button type="submit" class="btn btn-primary">Crear</button>
    </div>

</div>
</form>

</body>
</html>

resources/views/forms/taxUpdateForm.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>Edit Tax</title>
</head>
<body>
<form  action="/admin/tax/{{ $tax->id }}" method="POST" id="demo-form" enctype="multipart/form-data">
    @csrf
    
<div class="row">

  <div class="col-md-4 col-sm-12 col-xs-12 form-group">
    <label for="fullname">Amount  :</label>
    <input type="numeric" name="amount" class="form-control" value="{{ $tax->amount }}" required />
  </div>

  <br>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Editar</button>
    </div>

</div>
</form>

</body>
</html>